baseURL = "https://voidspacexyz.github.io/"
languageCode = "en-us"
title = "My Digital Garden"
theme = "blog-theme"
copyright = "All content licensed under CC-By-SA-4.0 or above unless otherwise noted"
enableGitInfo = true
enableRobotsTXT = true
ignorefiles = ["draft/.*"]

[params]
name = "VoidSpaceXYZ"
description = "Views from the eyes of an intersectionalist"
initials = "V"
googleAnalytics = ""

[[params.social]]
name = "Github"
link = "https://github.com/voidspacexyz"
icon = "fab fa-github"

[[params.social]]
name = "Gitlab"
link = "https://gitlab.com/voidspacexyz"
icon = "fab fa-gitlab"

[[params.social]]
name = "LinkedIn"
link = "https://in.linkedin.com/in/ramaseshan-s-8793a558"
icon = "fab fa-linkedin-in"

[[params.social]]
name = "Twitter"
link = "https://twitter.com/voidspacexyz"
icon = "fab fa-twitter"

[[params.social]]
name = "Instagram"
link = "https://www.instagram.com/voidspacexyz"
icon = "fab fa-instagram"

[[params.social]]
name = "Mastodon"
link = "https://mastodon.xyz/@voidspacexyz"
icon = "fab fa-mastodon"


[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Digital Garden"
url = "/garden/"
weight = 2
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3
[[menu.main]]
name = "Library"
url = "/library/"
weight = 4
[[menu.main]]
name = "About"
url = "/about/"
weight = 5
[[menu.main]]
name = "Resume"
url = "https://gitconnected.com/voidspacexyz/resume"
weight = 6


[taxonomies]
garden_tags = 'garden_tags'
project_tags = 'project_tags'
library_tags = 'library_tags'


[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = true
[markup.goldmark.parser.attribute]
block = false
title = true
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.highlight]
# Choose from https://xyproto.github.io/splash/docs/all.html
style = 'monokailight'
